services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: firefly-api
    env_file:
      - .env.docker
    ports:
      - "3000:3000"
    depends_on:
      mongo:
          condition: service_healthy
      redis: 
        condition: service_healthy
    networks:
      - firefly-network
    retstart: unless-stopped
    healthcheck:
      test: [
        "CMD-SHELL",
         "node -e \"fetch('http://localhost:3000/health').then(r => process.exit(r.ok ? 0 : 1)).catch(() => process.exit(1))\""
         ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s

  mongo:
    image: mongo:8
    container_name: firefly-mongodb
    ports:
      - "27017:27017"
    volumes:
      - firefly-mongo-data:/data/db
    networks:
      - firefly-network
    restart: unless-stopped
    healthcheck:
      test: [
        "CMD-SHELL", 
        "mongosh --quiet --eval \"db.adminCommand('ping').ok\" | grep 1"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
  redis:
    image: redis:8-alpine
    container_name: firefly-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - firefly-redis-data:/data
    networks:
      - firefly-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  firefly-network:
    driver: bridge

volumes: 
  firefly-mongo-data:
  firefly-redis-data:
